# Generated by Django 2.2 on 2021-11-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficulty',
            new_name='difficluty',
        ),
    ]
