# Generated by Django 2.2 on 2021-11-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20211121_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficluty',
            new_name='difficulty',
        ),
    ]
